[project]
name = "gnuradio-companion"
description = "GNU Radio Companion"
version = "0.1.0"
authors = [
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

